### ISSUE TITLE
native JS document.ready method

### ISSUE THREAD

**Issue by premasagar** [premasagar/sqwidget#1]
For the Sqwidget loader script, which is executed before jQuery is present in the document, we need a simple, stripped-down version of jQuery's document.ready() method - one that works in native JavaScript. It attempts to fire as soon as the DOM is complete, but falls back to window.onload.

Performance is optimised for modern browsers; needs to function in older browsers.

**Comment by padolsey** [comment]
Added: http://github.com/premasagar/sqwidget/commit/cec9f5f7166ca45a805b09a9bb5437f74308565b
