### ISSUE TITLE
Convert scaffold to yeoman

### ISSUE THREAD

**Issue by purge** [premasagar/sqwidget#106]
Will allow us to have better options for overriding file replaces.

**Comment by adhipg** [comment]
I think we'll have to do this. It's pretty unusable right now - pretty confusing for someone to get started with it.

**Comment by adhipg** [comment]
Done. New scaffold at https://github.com/adhipg/generator-sqwidget

I think that sqwidget should be independent of this generator. Sqwidget should **just** be a bower plugin.
