### ISSUE TITLE
Breaks in Edge/IE 11

### ISSUE THREAD

**Issue by btbjosh** [premasagar/sqwidget#110]
I am using Sqwidget and it was working fine but has since stopped working in IE 11/Edge recently.

Fails within `getWidgetParams`with the error,

`SCRIPT5022: No widget source defined (set data-sqwidget-url)
sqwidget.js (33,18282)` which is weird because it has these values set but the element obj that is supposed to be fetched in `getWidgetParams` is undefined. So i'm not sure what is specific to the breakage in IE/edge.

Thoughts or ideas?

Works fine in all other browsers. Not sure if anyone has any answers or even still looks at these issues. 😬

**Comment by elise-boinnot** [comment]
Hi @btbjosh,
I had this issue I solved it by passing the widget url in data-sqwidget attribute instead of data-sqwidget-url. I found that the empty data-sqwidget attribute causes the issue you described in IE.

**Comment by btbjosh** [comment]
Wow. Wish i would have figured that one out. I just re-built the entire thing using preact/webpack instead. 😝 

Thanks for the tip, though!
