### ISSUE TITLE
tmpl ignores new lines - this prevents proper embed code formatting

### ISSUE THREAD

**Issue by premasagar** [premasagar/sqwidget#44]

**Comment by grasuth** [comment]
this a result of the compilation from html to js.

**Comment by premasagar** [comment]
Ah, of course. We could potentially reverse it, in the case of the embed code by prepending four consecutive spaces with a /n newline. A bit hacky. Not sure if that should be in Sqwidget core or in the widget controller.

**Comment by premasagar** [comment]
Adding '\n' to the end of each line in the micro-template resolves this.
