### ISSUE TITLE
Clarify use of async="async" in sqwidget.js <script> and conflict with Sqwidget.globalConfig in host page

### ISSUE THREAD

**Issue by premasagar** [premasagar/sqwidget#48]
Currently, we are planning to have the embed code use `async="async"` in the sqwidget.js <script> tag. E.g. 

```
<script src="sqwidget/sqwidget.js" type="text/javascript" async="async"></script>
```

This prevents Sqwidget from blocking rendering of the host page, and is currently supported at least by Firefox, probably Chrome by now too.

In general, this is a good thing, but there is a conflict when combined with an inline script in the host page for setting up defaults for Sqwidget, such as:

```
<script type="text/javascript">
    // global sqwidget configuration options, if needed
    Sqwidget.globalConfig({
        development: true,
        experimental: true,
        automatic: true,
        charset: 'utf-8',
        basePath: '.',
        pluginPath: 'sqwidget/plugins/'
    });
</script>
```

Before the first embed code is deployed, this should be clarified. Either we need to exclude `async` from the script element, or we need another mechanism for setting config from the host page. Or, we simply warn advanced users who want to add a config that they should remove `async` from the page when they do so. Hmmm, the last option maybe?

**Comment by grasuth** [comment]
No default config is needed, so this can be removed from the embed code file and slightly tweaked, emerge as settings for a template.
