### ISSUE TITLE
Documentation: manifest or whole widget options for templates

### ISSUE THREAD

**Issue by premasagar** [premasagar/sqwidget#49]
## For the documentation:

Here are two strong possibilities for widget packaging patterns that have emerged in recent discussions:

1) everything contained within one single template file (e.g. descriptor JSON, CSS, JS, dataURI images and HTML template)
- this is excellent for giving the minimum HTTP request (i.e. just one)
- its disadvanatage is that it could only be allowed to be cached for more than a short amount of time if it's not going to be changed in future (e.g. to have new feature, bug fixes, new data sources). This might be ok for some widgets, but probably not most. 

2) Have a descriptor file that contains minimal meta data, plus a link to the template file. The template file then contains everything else.
- the descriptor file could have a short cache time, while the template file could have a long cache time
- the trade-off with having two HTTP requests feels worth it, since the second request will be cached for a long time
- whenever the template file needs to be updated, then it's URL is also changed (e.g. by the addition of a version number) and the descriptor file updated with the new URL
- it would allow multiple templates for different platforms and clients (e.g. IE6, Safari 2, Adobe Air, various mobile platforms)

**Comment by grasuth** [comment]
Done template to src change. But there's good stuff here. Renaming.
