### ISSUE TITLE
tim (microtemplater) doesn't allow spaces in template tags

### ISSUE THREAD

**Issue by grasuth** [premasagar/sqwidget#63]
eg {{ thing }} doesn't substitute, where {{thing}} does.  This is changed from resig's microtemplater

**Comment by premasagar** [comment]
Hmmm. Interesting. This would be easy to change in `tim`. But I'm inclined to keep it simple and strict, for simplicity and the nano performance gains this would give. What do you think?

**Comment by grasuth** [comment]
I'm thinking its ok as it is for now.  I've updates the sqwidget tests to allow this to work ok.
