### ISSUE TITLE
New Repo

### ISSUE THREAD

**Issue by purge** [premasagar/sqwidget#86]
unless this is going to be backwards compatible with sqwidget 1 this should really be in its own separate repository.

**Comment by premasagar** [comment]
Or we can tag sqwidget v1.0 and update the repo with the new way. The
wiki's going to need to be updated with all the up-to-date info. It'd be
good to archive the v1.0 wiki info first.

**Comment by purge** [comment]
as long there is no parallel development on both this will work.

**Comment by premasagar** [comment]
No, there won't be any further work on Sqwidget v1.0

On 25 September 2013 14:46, Simon Elliott notifications@github.com wrote:

> as long there is no parallel development on both this will work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/premasagar/sqwidget/issues/86#issuecomment-25086860
> .

## 

_Premasagar Rose_, Dharmafly http://dharmafly.com
dharmafly.com / 07941 192398
premasagar.com
twitter.com/premasagar
L4RP.com
asyncjs.com

**Comment by purge** [comment]
OK, tag it and bag it. i'll do all the new work against development till we're ready then overwrite master when we're ready for a release
