### ISSUE TITLE
RFC: amd module directory

### ISSUE THREAD

**Issue by purge** [premasagar/sqwidget#98]
at the moment i'm including a number of libraries which can be loaded using a normalised name. this is due to limitations of AMD's design. however this could be quite useful since they are not included in the optimised stage they can be required by any package and they will only be fetched once.

Do we make this list longer, or rely on people using absolute CDN urls which will also only be loaded once.

**Comment by adhipg** [comment]
I think CDN is a better choice. The more libraries we add here the more opinionated we become.
