### ISSUE TITLE
Bower publish

### ISSUE THREAD

**Issue by adhipg** [premasagar/sqwidget#99]
Can we start publishing this to bower? That makes installing the widgets _much_ easier.

**Comment by premasagar** [comment]
Good idea.

**Comment by adhipg** [comment]
We are already using it as a private thing. That involves cloning the repo yourself and then doing a `bower link`.

Publishing sqwidget just automates that.
Waiting for this to get into dev so that we can publish it.

**Comment by purge** [comment]
It's already an npm module so you can use that config as a basis for the
bower one (i think they are quite similar now (prepublish, postinstall).
one thing that happens with the npm install is that it installs the grunt
template to your local grunt-init so you can use it by typing.

grunt-init sqwidget
<answer questions>

**Comment by adhipg** [comment]
Yeah, I'll publish it to bower in a bit.
